name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Cache LLaMA-3B model
      uses: actions/cache@v3
      with:
        path: /app/llama3
        key: ${{ runner.os }}-llama3-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-llama3-

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/fastapi-llama3:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max